### ISSUE TITLE
[documentation] Client Library documentation - Broken link

### ISSUE THREAD

**Issue by hradhakrishnan** [googleapis/python-grpc-google-iam-v1#35] opened 2023-03-08 13:37 UTC
Broken link to the client Library Documentation

[Client Library Documentation](https://cloud.google.com/python/docs/reference/grpc-iam/latest)

Sources:
1. This repo ReadME. 
2. https://pypi.org/project/grpc-google-iam-v1/
3. https://cloud.google.com/python/docs/reference. -> https://cloud.google.com/python/docs/reference/grpc-iam/latest

**Comment by parthea** [comment] 2023-11-30 19:41
Closing as the documentation no longer shows 404, however the content is empty. The issue is tracked in https://github.com/googleapis/python-grpc-google-iam-v1/issues/71

**Closed as completed by parthea** 2023-11-30 19:41 UTC
Labels: api: iam
