### ISSUE TITLE
Getting  ImportError: dynamic module does not define init function (initcygrpc)

### ISSUE THREAD

**Issue by rajk1729** [googleapis/python-grpc-google-iam-v1#37] opened 2023-03-24 13:19 UTC
grpc-google-iam-v1                0.12.3
grpcio                            1.41.1
google-cloud-iam                  1.0.3
google-cloud-secret-manager       1.0.2

#### Environment details

  - OS type and version: Mac Ventura 13
  - Python version: `python 2.7.18`
  - pip version: `20.3.4`
  - `grpc-google-iam-v1` version: `pip show grpc-google-iam-v1`

#### Steps to reproduce

  1. Installed grpc-google-iam-v1 and google-cloud-secret-manager
  2. On using import for secretmanager which internallyt uses gRPC, following error trace comes:
  grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dynamic module does not define init function (initcygrpc)

**Comment by parthea** [comment] 2023-11-15 19:32
Closing as a duplicate of https://github.com/grpc/grpc/issues/32717

**Closed as completed by parthea** 2023-11-15 19:32 UTC
Labels: api: iam
